# Generated by Django 4.2 on 2023-04-27 02:24

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('mean', models.CharField(max_length=255)),
                ('spell', models.CharField(max_length=255)),
                ('wordType', models.CharField(max_length=255)),
                ('url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle.topic')),
            ],
        ),
        migrations.CreateModel(
            name='myWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('saveF', models.BooleanField(default=0)),
                ('delete', models.BooleanField(default=0)),
                ('url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle.users')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle.words')),
            ],
        ),
        migrations.CreateModel(
            name='historyTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('mean', models.TextField()),
                ('delete', models.BooleanField(default=0)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle.users')),
            ],
        ),
        migrations.CreateModel(
            name='historyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('numberQT', models.IntegerField(default=0)),
                ('numberQF', models.IntegerField(default=0)),
                ('timeStart', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 9, 24, 32, 772256))),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle.users')),
            ],
        ),
    ]
