# Generated by Django 4.2 on 2023-05-10 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyresult',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 21, 16, 57, 493007)),
        ),
        migrations.AlterField(
            model_name='mywords',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='words',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handle.topic'),
        ),
        migrations.AlterField(
            model_name='words',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
