# Generated by Django 4.2 on 2023-05-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0002_alter_historyresult_timestart_alter_mywords_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyresult',
            name='timeStart',
        ),
        migrations.AddField(
            model_name='historyresult',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handle.topic'),
        ),
    ]
